### ISSUE TITLE
使用tun版clash无法正常运行

### ISSUE THREAD

**Issue by Mosney** [frainzy1477/luci-app-clash#158]
### 使用环境：
OpenWrt amd64 19.07.1、luci-app-clash 1.5.2
分别使用了release和luci中提到的两份预编译clash tun（https://github.com/comzyh/clash/releases，https://github.com/frainzy1477/clashtun/releases）
#### clashtun+启用游戏规则
在概览中可以观察到启动几秒钟后进程结束，输出步骤卡在 Restarting Dnsmasq。
同时clash输出日志
` Parse config error: yaml: line 1383: did not find expected key`
生成的的配置文件中1383行内容是：
`#*******GAME-RULE-START**********#`
#### clashtun+禁用游戏规则
日志出现类似 #155 的内容
```
time="2020-02-08T06:27:43Z" level=warning msg="[UDP] dial DIRECT error: listen udp :0: socket: too many open files"
time="2020-02-08T06:27:44Z" level=warning msg="[UDP] dial DIRECT error: listen udp :0: socket: too many open files"
time="2020-02-08T06:27:44Z" level=warning msg="dial MATCH error: dial tcp4 64.136.210.161:6894: socket: too many open files"
time="2020-02-08T06:27:44Z" level=warning msg="dial Domestic error: dial tcp4 221.217.48.120:51413: socket: too many open files"
```

#### 最后又测试了一下官方release的17.1 clash内核+启用游戏规则，跟上面tun内核一样的错误日志
` "Parse config error: yaml: line 1383: did not find expected key"`

**Comment by frainzy1477** [comment]
安装1.5.3把

**Comment by Mosney** [comment]
另外发现开启游戏规则后组合生成的配置文件部分有问题
     
```
experimental:
  ignore-resolve-fail: true

tun:
 enable: true
 device-url: dev://utun
 dns-listen: 0.0.0.0:53

dns:
 enable: true
 listen: 0.0.0.0:5300
 enhanced-mode: fake-ip
 fake-ip-range: 198.18.0.1/16
 nameserver:  
  - 114.114.114.114    
  - tls://118.89.110.78:853
  - tls://47.96.179.163:853
  - udp://8.8.8.8:53
  - udp://8.8.4.4:53
  - tcp://1.1.1.1
  
  
 
Proxy:
```

**Comment by Mosney** [comment]
> 安装1.5.3把

好，我试试

**Comment by frainzy1477** [comment]
嗯，1.5.2问题是先要在端口设置页，保存并应用

**Comment by Mosney** [comment]
@frainzy1477 麻烦看一下 #144

**Comment by Mosney** [comment]
1.5.3生成的这个配置似乎也不太对
```

tun:
 enable: true
 device-url: dev://utun
 dns-listen: 0.0.0.0:53

#authentication:
# - "user1:pass1"

#hosts:
# '*.clash.dev': 127.0.0.1
# 'alpha.clash.dev': '::1'

dns:
 enable: true
 listen: 0.0.0.0:5300
 enhanced-mode: fake-ip
 fake-ip-range: 198.18.0.1/16
 nameserver:  
  - udp://114.114.114.114    
  - tls://118.89.110.78:853
  - tls://47.96.179.163:853
  - udp://8.8.8.8:53
  - udp://8.8.4.4:53
  - tcp://1.1.1.1
 fallback:
  - tls://118.89.110.78:853
  - tls://47.96.179.163:853
  - tcp://1.1.1.1
  - tcp://8.8.8.8
 fallback-filter:
  geoip: true
  ipcidr:
    - 240.0.0.0/4 

  
```
