### ISSUE TITLE
v1.5.9 因自定义DNS问题导致无法使用

### ISSUE THREAD

**Issue by Scorpion4286** [frainzy1477/luci-app-clash#187]
环境：OpenWrt官方源19.07.1
问题：升级1.5.9后无法使用

现象：运行中的配置自
```
fallback-filter:
  geoip: true
  ipcidr:
    - 240.0.0.0/4
```
后为空。
如不使用自定义DNS，则提示config.yaml不存在。

配置文件问题可以排除，是从1.5.8继承过来的。
有按照提示在自定义DNS后面加空行。

另：偶发/etc/config/clash文件损坏，文件大小变为0kb，目前遇到的情况都是执行停用客户端导致。
前几个版本就遇到的问题，这里一并提了。
