### ISSUE TITLE
TUN DNS 设置 问题

### ISSUE THREAD

**Issue by mephisX** [frainzy1477/luci-app-clash#250]
![image](https://user-images.githubusercontent.com/30206556/80705833-c1cb7080-8b19-11ea-8980-2246991257fa.png)
为什么里面的 cfg 改成如下之后，TUN 就只有 IP 了，没有域名。
```
 enhanced-mode: redir-host
 hosts:
  ip.jb.tn: 127.0.0.1
 nameserver:  
  - 1.2.4.8
  - 119.29.29.29
  - https://dns.alidns.com/dns-query
 fallback:
  - https://dns.google/dns-query
  - tls://1.1.1.1:853
  - https://1.1.1.1/dns-query
  - tls://8.8.8.8:853
 fallback-filter:
  geoip: true
  ipcidr:
    - 240.0.0.0/4 
```

如果是使用 内置的 CFG 就没问题。
