### ISSUE TITLE
路由器上可以正常访问 IPv6 网站，连接路由器的设备不能正常访问 IPv6 网站

### ISSUE THREAD

**Issue by cielpy** [frainzy1477/luci-app-clash#354]
配置如下：

```yaml
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
ipv6: true
allow-lan: true
bind-address: "*"
mode: rule
log-level: info
external-controller: 0.0.0.0:9090
secret: "123456"
external-ui: "./dashboard"
 



dns:
  enable: true
  listen: 0.0.0.0:5300   
  ipv6: true
  enhanced-mode: redir-host
  nameserver:
   - udp://127.0.0.1:6053
```
 
在路由器上：

```
root@OpenWrt:~# ping bbs6.ustc.edu.cn
PING bbs6.ustc.edu.cn (2001:da8:d800::3): 56 data bytes
64 bytes from 2001:da8:d800::3: seq=0 ttl=51 time=42.149 ms
64 bytes from 2001:da8:d800::3: seq=1 ttl=51 time=42.448 ms
^C
--- bbs6.ustc.edu.cn ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 42.149/42.298/42.448 ms
```

在连接路由器的设备上 

```
# ahhhh @ ahhhh-iMac in ~ [21:06:24] C:68
$ dig bbs6.ustc.edu.cn aaaa

; <<>> DiG 9.10.6 <<>> bbs6.ustc.edu.cn aaaa
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 57749
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;bbs6.ustc.edu.cn.		IN	AAAA

;; ANSWER SECTION:
bbs6.ustc.edu.cn.	295	IN	AAAA	2001:da8:d800::3

;; Query time: 1 msec
;; SERVER: 192.168.33.1#53(192.168.33.1)
;; WHEN: Mon Mar 08 21:06:33 CST 2021
;; MSG SIZE  rcvd: 78


# ahhhh @ ahhhh-iMac in ~ [21:06:33]
$ dig bbs6.ustc.edu.cn

; <<>> DiG 9.10.6 <<>> bbs6.ustc.edu.cn
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 12184
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;bbs6.ustc.edu.cn.		IN	A

;; AUTHORITY SECTION:
bbs6.ustc.edu.cn.	1	IN	SOA	ns.ustc.edu.cn. james.ustc.edu.cn. 2021030112 1200 900 604800 600

;; Query time: 1 msec
;; SERVER: 192.168.33.1#53(192.168.33.1)
;; WHEN: Mon Mar 08 21:06:36 CST 2021
;; MSG SIZE  rcvd: 117
```
